# Generated by Django 3.1.7 on 2021-03-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_Nm', models.CharField(max_length=85, verbose_name='Artikel naam')),
                ('art_Omschr', models.TextField(blank=True, null=True, verbose_name='Omschrijving')),
                ('art_Image', models.ImageField(blank=True, max_length=250, null=True, upload_to='', verbose_name='Afbeelding')),
                ('art_Prijs', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
