# Generated by Django 3.2.3 on 2021-05-27 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mijnWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'verbose_name_plural': 'artikelen'},
        ),
    ]
