# Generated by Django 3.2.3 on 2021-05-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mijnWebApp', '0002_alter_artikel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoetsMoment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptm_Moment', models.DateTimeField(auto_now_add=True, verbose_name='Poetsmoment')),
                ('ptm_Interval', models.DurationField(null=True, verbose_name='Poetsinterval')),
            ],
        ),
    ]
