# Generated by Django 3.2.3 on 2021-05-28 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mijnWebApp', '0003_poetsmoment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prf_BirthDate', models.DateField(blank=True, null=True, verbose_name='Geboortedatum')),
                ('prf_Gender', models.CharField(choices=[('M', 'Man'), ('F', 'Vrouw')], max_length=1, verbose_name='Geslacht')),
                ('prf_User', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='poetsmoment',
            name='ptm_User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mijnWebApp.profile', verbose_name='Bij Gebruiker'),
        ),
    ]
