# Generated by Django 3.2.3 on 2021-05-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mijnWebApp', '0004_auto_20210528_0855'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artikel',
        ),
        migrations.AlterModelOptions(
            name='poetsmoment',
            options={'verbose_name_plural': 'poetsmomenten'},
        ),
        migrations.AlterField(
            model_name='poetsmoment',
            name='ptm_Interval',
            field=models.DurationField(blank=True, null=True, verbose_name='Poetsinterval'),
        ),
    ]
