# Generated by Django 3.2.3 on 2021-05-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mijnWebApp', '0005_auto_20210528_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='poetsmoment',
            name='ptm_Activity',
            field=models.CharField(choices=[('P', 'Poetsen'), ('R', 'Raggen'), ('F', 'Flossen'), ('M', 'Mondwater')], default='P', max_length=1, verbose_name='Activiteit'),
        ),
        migrations.AddField(
            model_name='poetsmoment',
            name='ptm_Notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notities'),
        ),
        migrations.AddField(
            model_name='poetsmoment',
            name='ptm_Toothpaste',
            field=models.CharField(choices=[('F', 'Met Fluor'), ('N', 'Normaal')], default='F', max_length=1, verbose_name='Type Tandpasta'),
        ),
        migrations.AddField(
            model_name='profile',
            name='prf_DentalRating',
            field=models.IntegerField(default=0, verbose_name='Tandheelkundige beoordeling'),
        ),
    ]
